version: 0.2

phases:
  pre-build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build